In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.naive_bayes import GaussianNB

import sys
print(sys.version)

golf_file = "golf.csv"

# Open the file for reading and read in data
golf_file_handler = open(golf_file, "r")
golf_data = pd.read_csv(golf_file_handler, sep=";")
golf_file_handler.close()

golf_data.head(100)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

,Outlook,Temperature,Temperature_Category,Humidity,Humidity_Category,Windy,Play
0,overcast,83,hot,86,high,False,yes
1,overcast,64,cool,65,normal,True,yes
2,overcast,72,mild,90,high,True,yes
3,overcast,81,hot,75,normal,False,yes
4,rainy,70,mild,96,high,False,yes
5,rainy,68,cool,80,normal,False,yes
6,rainy,65,cool,70,normal,True,no
7,rainy,75,mild,80,normal,False,yes
8,rainy,71,mild,91,high,True,no
9,sunny,85,hot,85,high,False,no
10,sunny,80,hot,90,high,True,no
11,sunny,72,mild,95,high,False,no
12,sunny,69,cool,70,normal,False,yes
13,sunny,75,mild,70,normal,True,yes

In [2]:
# Data cleaning, we replace the strings with numbers
d = {'sunny': 1, 'overcast': 2, 'rainy': 3}
golf_data.Outlook = [d[item] for item in golf_data.Outlook.astype(str)]
golf_data.head(100)

,Outlook,Temperature,Temperature_Category,Humidity,Humidity_Category,Windy,Play
0,2,83,hot,86,high,False,yes
1,2,64,cool,65,normal,True,yes
2,2,72,mild,90,high,True,yes
3,2,81,hot,75,normal,False,yes
4,3,70,mild,96,high,False,yes
5,3,68,cool,80,normal,False,yes
6,3,65,cool,70,normal,True,no
7,3,75,mild,80,normal,False,yes
8,3,71,mild,91,high,True,no
9,1,85,hot,85,high,False,no
10,1,80,hot,90,high,True,no
11,1,72,mild,95,high,False,no
12,1,69,cool,70,normal,False,yes
13,1,75,mild,70,normal,True,yes

In [3]:
# Split the datatset into 70% train and 30% test data
train, test = train_test_split(golf_data,test_size=0.3, random_state=0)

# We need to reset the index, so that we can the test set use independently from the train dataset
test=test.reset_index(drop=True)

# initialise Gaussian Naive Bayes
# https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html 
naive_b = GaussianNB()

# lets take a look in the test set
print(test[['Outlook','Temperature','Humidity','Windy','Play']])

   Outlook  Temperature  Humidity  Windy Play
0        3           71        91   True   no
1        3           65        70   True   no
2        3           70        96  False  yes
3        1           72        95  False   no
4        2           72        90   True  yes

In [4]:
# Train the naive bayes model with the parameters and the classification to learn from
naive_b.fit(train[['Outlook','Temperature','Humidity','Windy']], train[['Play']])

# build a dataframe to show the expected vs predicted values
prediction_array=naive_b.predict(test[['Outlook','Temperature','Humidity','Windy']])
prediction_dataframe=pd.DataFrame(data=prediction_array, columns=["prediction"])
prediction_dataframe['result']=test['Play']

print (prediction_dataframe)

# Use the score function and output the prediction accuracy
print ("Naive Bayes Accuracy:", naive_b.score(test[['Outlook','Temperature','Humidity','Windy']], test[['Play']]))

  prediction result
0        yes     no
1        yes     no
2        yes    yes
3         no     no
4        yes    yes
Naive Bayes Accuracy: 0.6

C:\Users\tima268\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)